// Auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// Dashboard
export const FETCH_DASHBOARD_REQUEST = "FETCH_DASHBOARD_REQUEST";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";

// Pings
export const UPDATE_PING_REQUEST = "UPDATE_PING_REQUEST";
export const UPDATE_PING_SUCCESS = "UPDATE_PING_SUCCESS";
export const UPDATE_PING_FAIL = "UPDATE_PING_FAIL";

export const DELETE_PING_REQUEST = "DELETE_PING_REQUEST";
export const DELETE_PING_SUCCESS = "DELETE_PING_SUCCESS";
export const DELETE_PING_FAIL = "DELETE_PING_FAIL";

// Hospitals
export const FETCH_HOSPITALS_REQUEST = "FETCH_HOSPITALS_REQUEST";
export const FETCH_HOSPITALS_SUCCESS = "FETCH_HOSPITALS_SUCCESS";
export const FETCH_HOSPITALS_FAIL = "FETCH_HOSPITALS_FAIL";

export const DELETE_HOSPITAL_REQUEST = "DELETE_HOSPITAL_REQUEST";
export const DELETE_HOSPITAL_SUCCESS = "DELETE_HOSPITAL_SUCCESS";
export const DELETE_HOSPITAL_FAIL = "DELETE_HOSPITAL_FAIL";
export const DELETE_HOSPITAL_RESET = "DELETE_HOSPITAL_RESET";

// Chats
export const GET_ACTIVE_CHATS_REQUEST = "GET_ACTIVE_CHATS_REQUEST";
export const GET_ACTIVE_CHATS_SUCCESS = "GET_ACTIVE_CHATS_SUCCESS";
export const GET_ACTIVE_CHATS_FAIL = "GET_ACTIVE_CHATS_FAIL";

export const GET_HOSPITAL_CHAT_HISTORY_REQUEST =
  "GET_HOSPITAL_CHAT_HISTORY_REQUEST";
export const GET_HOSPITAL_CHAT_HISTORY_SUCCESS =
  "GET_HOSPITAL_CHAT_HISTORY_SUCCESS";
export const GET_HOSPITAL_CHAT_HISTORY_FAIL = "GET_HOSPITAL_CHAT_HISTORY_FAIL";

export const NEW_PING_FAIL = "NEW_PING_FAIL";
export const NEW_PING_REQUEST = "NEW_PING_REQUEST";
export const NEW_PING_SUCCESS = "NEW_PING_SUCCESS";
export const NEW_PING_RESET = "NEW_PING_RESET";
export const UPDATE_PING_RESET = "UPDATE_PING_RESET";
export const DELETE_PING_RESET = "DELETE_PING_RESET";

export const DELETE_CHAT_REQUEST = "DELETE_CHAT_REQUEST";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAIL = "DELETE_CHAT_FAIL";
export const DELETE_CHAT_RESET = "DELETE_CHAT_RESET";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";

// Action Types
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET"

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";
export const UPDATE_REVIEW_RESET = "UPDATE_REVIEW_RESET";

export const UPDATE_HOSPITAL_PROFILE_REQUEST =
  "UPDATE_HOSPITAL_PROFILE_REQUEST";
export const UPDATE_HOSPITAL_PROFILE_SUCCESS =
  "UPDATE_HOSPITAL_PROFILE_SUCCESS";
export const UPDATE_HOSPITAL_PROFILE_FAIL = "UPDATE_HOSPITAL_PROFILE_FAIL";
export const UPDATE_HOSPITAL_PROFILE_RESET = "UPDATE_HOSPITAL_PROFILE_RESET";

export const UPDATE_HOSPITAL_PASSWORD_REQUEST =
  "UPDATE_HOSPITAL_PASSWORD_REQUEST";
export const UPDATE_HOSPITAL_PASSWORD_SUCCESS =
  "UPDATE_HOSPITAL_PASSWORD_SUCCESS";
export const UPDATE_HOSPITAL_PASSWORD_FAIL = "UPDATE_HOSPITAL_PASSWORD_FAIL";
export const UPDATE_HOSPITAL_PASSWORD_RESET = "UPDATE_HOSPITAL_PASSWORD_RESET";

export const UPDATE_PATIENT_PROFILE_REQUEST = "UPDATE_PATIENT_PROFILE_REQUEST";
export const UPDATE_PATIENT_PROFILE_SUCCESS = "UPDATE_PATIENT_PROFILE_SUCCESS";
export const UPDATE_PATIENT_PROFILE_FAIL = "UPDATE_PATIENT_PROFILE_FAIL";
export const UPDATE_PATIENT_PROFILE_RESET = "UPDATE_PATIENT_PROFILE_RESET";

export const UPDATE_PATIENT_PASSWORD_REQUEST =
  "UPDATE_PATIENT_PASSWORD_REQUEST";
export const UPDATE_PATIENT_PASSWORD_SUCCESS =
  "UPDATE_PATIENT_PASSWORD_SUCCESS";
export const UPDATE_PATIENT_PASSWORD_FAIL = "UPDATE_PATIENT_PASSWORD_FAIL";
export const UPDATE_PATIENT_PASSWORD_RESET =
  "export const UPDATE_PATIENT_PASSWORD_RESET";

// Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
export const SET_MESSAGES = "SET_MESSAGES";

export const AVAILABLE_HOSPITALS = [
  "Aminu Kano Teaching Hospital",
  "Yusuf Dantsoho Memorial Hospital",
  "Ahmadu Bello University Teaching Hospital",
  "Garki Hospital",
  "Lagos University Teaching Hospital",
];
