// Auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// Dashboard
export const FETCH_DASHBOARD_REQUEST = "FETCH_DASHBOARD_REQUEST";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";

// Pings
export const UPDATE_PING_REQUEST = "UPDATE_PING_REQUEST";
export const UPDATE_PING_SUCCESS = "UPDATE_PING_SUCCESS";
export const UPDATE_PING_FAIL = "UPDATE_PING_FAIL";

export const DELETE_PING_REQUEST = "DELETE_PING_REQUEST";
export const DELETE_PING_SUCCESS = "DELETE_PING_SUCCESS";
export const DELETE_PING_FAIL = "DELETE_PING_FAIL";

// Hospitals
export const FETCH_HOSPITALS_REQUEST = "FETCH_HOSPITALS_REQUEST";
export const FETCH_HOSPITALS_SUCCESS = "FETCH_HOSPITALS_SUCCESS";
export const FETCH_HOSPITALS_FAIL = "FETCH_HOSPITALS_FAIL";

export const DELETE_HOSPITAL_REQUEST = "DELETE_HOSPITAL_REQUEST";
export const DELETE_HOSPITAL_SUCCESS = "DELETE_HOSPITAL_SUCCESS";
export const DELETE_HOSPITAL_FAIL = "DELETE_HOSPITAL_FAIL";
export const DELETE_HOSPITAL_RESET = "DELETE_HOSPITAL_RESET";

// Chats
export const GET_ACTIVE_CHATS_REQUEST = "GET_ACTIVE_CHATS_REQUEST";
export const GET_ACTIVE_CHATS_SUCCESS = "GET_ACTIVE_CHATS_SUCCESS";
export const GET_ACTIVE_CHATS_FAIL = "GET_ACTIVE_CHATS_FAIL";

export const GET_CHAT_HISTORY_REQUEST = "GET_CHAT_HISTORY_REQUEST";
export const GET_CHAT_HISTORY_SUCCESS = "GET_CHAT_HISTORY_SUCCESS";
export const GET_CHAT_HISTORY_FAIL = "GET_CHAT_HISTORY_FAIL";

export const NEW_PING_FAIL = "NEW_PING_FAIL";
export const NEW_PING_REQUEST = "NEW_PING_REQUEST";
export const NEW_PING_SUCCESS = "NEW_PING_SUCCESS";
export const NEW_PING_RESET = "NEW_PING_RESET";
export const UPDATE_PING_RESET = "UPDATE_PING_RESET";
export const DELETE_PING_RESET = "DELETE_PING_RESET";

export const DELETE_CHAT_REQUEST = "DELETE_CHAT_REQUEST";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAIL = "DELETE_CHAT_FAIL";
export const DELETE_CHAT_RESET = "DELETE_CHAT_RESET";

// Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const AVAILABLE_HOSPITALS = [
  "Aminu Kano Teaching Hospital",
  "Yusuf Dantsoho Memorial Hospital",
  "Ahmadu Bello University Teaching Hospital",
  "Garki Hospital",
  "Lagos University Teaching Hospital",
];
