const disorders = [
    { "name": "headache" },
    { "name": "stomach ache" },
    { "name": "fever" },
    { "name": "cold" },
    { "name": "flu" },
    { "name": "allergy" },
    { "name": "malaria" },
    { "name": "typhoid" },
    { "name": "cholera" },
    { "name": "dengue" },
    { "name": "tuberculosis" },
    { "name": "pneumonia" },
    { "name": "diarrhea" },
    { "name": "asthma" },
    { "name": "hypertension" },
    { "name": "diabetes" },
    { "name": "hepatitis" },
    { "name": "HIV/AIDS" },
    { "name": "sickle cell anemia" },
    { "name": "anemia" },
    { "name": "measles" },
    { "name": "chickenpox" },
    { "name": "mumps" },
    { "name": "rubella" },
    { "name": "whooping cough" },
    { "name": "meningitis" },
    { "name": "yellow fever" },
    { "name": "ebola" },
    { "name": "lassa fever" },
    { "name": "zika virus" },
    { "name": "COVID-19" },
    { "name": "arthritis" },
    { "name": "back pain" },
    { "name": "migraine" },
    { "name": "dental pain" },
    { "name": "eye infection" },
    { "name": "ear infection" },
    { "name": "skin rash" },
    { "name": "eczema" },
    { "name": "psoriasis" },
    { "name": "dermatitis" },
    { "name": "scabies" },
    { "name": "ringworm" },
    { "name": "jaundice" },
    { "name": "appendicitis" },
    { "name": "ulcer" },
    { "name": "constipation" },
    { "name": "food poisoning" },
    { "name": "tooth decay" },
    { "name": "sinusitis" },
    { "name": "bronchitis" },
    { "name": "heart disease" },
    { "name": "stroke" },
    { "name": "kidney disease" },
    { "name": "urinary tract infection" },
    { "name": "sexually transmitted infection" },
    {"name": "high blood pressure"},
    {"name": "high cholesterol"},
    {"name": "heart attack"},
    {"name": "stroke"},
    {"name": "heart failure"},
    {"name": "angina"},
    {"name": "arrhythmia"},
    {"name": "atrial fibrillation"},
    {"name": "congestive heart failure"},
    {"name": "coronary artery disease"},
    {"name": "peripheral artery disease"},
    {"name": "deep vein thrombosis"},
    {"name": "pulmonary embolism"},
    {"name": "varicose veins"},
    {"name": "hemorrhoids"},
    {"name": "anal fissure"},
    {"name": "gastroesophageal reflux disease (GERD)"},
    {"name": "peptic ulcer disease"},
    {"name": "irritable bowel syndrome (IBS)"},
    {"name": "inflammatory bowel disease (IBD)"},
    {"name": "Crohn's disease"},
    {"name": "ulcerative colitis"},
    {"name": "diverticulitis"},
    {"name": "gallstones"},
    {"name": "liver cirrhosis"},
    {"name": "hepatitis"},
    {"name": "gastroenteritis"},
    {"name": "food poisoning"},
    {"name": "pancreatitis"},
    {"name": "diabetes mellitus"},
    {"name": "type 1 diabetes"},
    {"name": "type 2 diabetes"},
    {"name": "gestational diabetes"},
    {"name": "hypoglycemia"},
    {"name": "osteoporosis"},
    {"name": "rheumatoid arthritis"},
    {"name": "osteoarthritis"},
    {"name": "gout"},
    {"name": "fibromyalgia"},
    {"name": "lupus"},
    {"name": "multiple sclerosis"},
    {"name": "Parkinson's disease"},
    {"name": "Alzheimer's disease"},
    {"name": "dementia"},
    {"name": "migraine"},
    {"name": "tension headache"},
    {"name": "cluster headache"},
    {"name": "sinusitis"},
    {"name": "allergic rhinitis"},
    {"name": "asthma"},
    {"name": "chronic obstructive pulmonary disease (COPD)"},
    {"name": "pneumonia"},
    {"name": "bronchitis"},
    {"name": "emphysema"},
    {"name": "sleep apnea"},
    {"name": "insomnia"},
    {"name": "narcolepsy"},
    {"name": "restless legs syndrome"},
    {"name": "anxiety disorder"},
    {"name": "panic disorder"},
    {"name": "phobia"},
    {"name": "post-traumatic stress disorder (PTSD)"},
    {"name": "depression"},
    {"name": "bipolar disorder"},
    {"name": "schizophrenia"},
    {"name": "obsessive-compulsive disorder (OCD)"},
    {"name": "eating disorders"},
    {"name": "anorexia nervosa"},
    {"name": "bulimia nervosa"},
    {"name": "binge-eating disorder"},
    {"name": "substance use disorder"},
    {"name": "alcoholism"},
    {"name": "drug addiction"},
    {"name": "smoking addiction"},
    {"name": "attention deficit hyperactivity disorder (ADHD)"},
    {"name": "autism spectrum disorder (ASD)"},
    {"name": "intellectual disability"},
    {"name": "learning disabilities"},
    {"name": "dyslexia"},
    {"name": "dyscalculia"},
    {"name": "physical disabilities"},
    {"name": "hearing impairment"},
    {"name": "vision impairment"},
    {"name": "mobility impairment"},
    { "name": "gonorrhea" },
    { "name": "syphilis" },
    { "name": "chlamydia" },
    { "name": "herpes" },
    { "name": "warts" },
    { "name": "pelvic inflammatory disease" },
    { "name": "prostate issues" },
    { "name": "infertility" },
    { "name": "depression" },
    { "name": "anxiety" },
    { "name": "bipolar disorder" },
    { "name": "schizophrenia" },
    { "name": "epilepsy" },
    { "name": "seizure" },
    { "name": "substance abuse" },
    { "name": "alcoholism" },
    { "name": "malnutrition" },
    { "name": "vitamin deficiency" },
    { "name": "obesity" },
    { "name": "overweight" },
    { "name": "childhood obesity" },
    { "name": "pregnancy complications" },
    { "name": "menstrual pain" },
    { "name": "ovarian cysts" },
    { "name": "breast cancer" },
    { "name": "prostate cancer" },
    { "name": "lung cancer" },
    { "name": "cervical cancer" },
    { "name": "liver cancer" },
    { "name": "colon cancer" },
    { "name": "skin cancer" },
    { "name": "bladder cancer" },
    { "name": "thyroid cancer" },
    { "name": "leukemia" },
    { "name": "lymphoma" },
    { "name": "anaphylaxis" },
    { "name": "hypothyroidism" },
    { "name": "hyperthyroidism" },
    { "name": "gout" },
    { "name": "lupus" },
    { "name": "fibromyalgia" },
    { "name": "multiple sclerosis" },
    { "name": "parkinson's disease" },
    { "name": "alzheimer's disease" },
    { "name": "dementia" },
    { "name": "autism spectrum disorder" },
    { "name": "attention deficit hyperactivity disorder" },
    { "name": "speech disorder" },
    { "name": "hearing loss" },
    { "name": "vision loss" },
    { "name": "cataract" },
    { "name": "glaucoma" },
    { "name": "retinal detachment" },
    { "name": "macular degeneration" },
    { "name": "conjunctivitis" },
    { "name": "eye strain" },
    { "name": "dry eyes" },
    { "name": "insomnia" },
    { "name": "sleep apnea" },
    { "name": "restless legs syndrome" },
    { "name": "narcolepsy" },
    { "name": "psoriasis" },
    { "name": "vitiligo" },
    { "name": "herpes zoster" },
    { "name": "acne" },
    { "name": "alopecia" },
    { "name": "impetigo" },
    { "name": "boils" },
    { "name": "cellulitis" },
    { "name": "lyme disease" },
    { "name": "west nile virus" },
    { "name": "tetanus" },
    { "name": "rabies" },
    { "name": "botulism" },
    { "name": "diphtheria" },
    { "name": "pertussis" },
    { "name": "mononucleosis" },
    { "name": "streptococcal infection" },
    { "name": "staphylococcal infection" },
    { "name": "fungal infection" },
    { "name": "helminth infection" },
    { "name": "amoebiasis" },
    { "name": "giardiasis" },
    { "name": "cryptosporidiosis" },
    { "name": "trichomoniasis" },
    { "name": "toxoplasmosis" },
    { "name": "cysticercosis" },
    { "name": "echinococcosis" },
    { "name": "taeniasis" },
    { "name": "ascariasis" },
    { "name": "hookworm infection" },
    { "name": "trichuriasis" },
    { "name": "lymphatic filariasis" },
    { "name": "onchocerciasis" },
    { "name": "dracunculiasis" },
    { "name": "trypanosomiasis" },
    { "name": "leishmaniasis" },
    { "name": "schistosomiasis" },
    { "name": "strongyloidiasis" },
    { "name": "toxocariasis" },
    { "name": "scabies" },
    { "name": "pediculosis" },
    { "name": "myiasis" },
    { "name": "leprosy" },
    { "name": "tuberculosis" },
    { "name": "nontuberculous mycobacterial infection" },
    { "name": "tularemia" },
    { "name": "brucellosis" },
    { "name": "melioidosis" },
    { "name": "leptospirosis" },
    { "name": "rickettsial infection" },
    { "name": "q fever" },
    { "name": "ehrlichiosis" },
    { "name": "anaplasmosis" },
    { "name": "babesiosis" },
    { "name": "bartonellosis" },
    { "name": "cytomegalovirus infection" },
    { "name": "herpes simplex virus infection" },
    { "name": "human papillomavirus infection" },
    { "name": "varicella-zoster virus infection" },
    { "name": "respiratory syncytial virus infection" },
    { "name": "parainfluenza virus infection" },
    { "name": "adenovirus infection" },
    { "name": "rhinovirus infection" },
    { "name": "coronavirus infection" },
    { "name": "influenza virus infection" },
    { "name": "metapneumovirus infection" },
    { "name": "enterovirus infection" },
    { "name": "coxsackievirus infection" },
    { "name": "echovirus infection" },
    { "name": "parechovirus infection" },
    { "name": "astrovirus infection" },
    { "name": "calicivirus infection" },
    { "name": "norovirus infection" },
    { "name": "sapovirus infection" },
    { "name": "rotavirus infection" },
    { "name": "hepatitis A" },
    { "name": "hepatitis B" },
    { "name": "hepatitis C" },
    { "name": "hepatitis D" },
    { "name": "hepatitis E" },
    { "name": "adenoviral hepatitis" },
    { "name": "alcoholic hepatitis" },
    { "name": "autoimmune hepatitis" },
    { "name": "biliary atresia" },
    { "name": "cirrhosis" },
    { "name": "cryptogenic hepatitis" },
    { "name": "drug-induced liver injury" },
    { "name": "fatty liver disease" },
    { "name": "hemochromatosis" },
    { "name": "nonalcoholic steatohepatitis" },
    { "name": "primary biliary cirrhosis" },
    { "name": "primary sclerosing cholangitis" },
    { "name": "wilson's disease" },
    { "name": "acute liver failure" },
    { "name": "chronic liver disease" },
    { "name": "liver transplant" },
    { "name": "acute kidney injury" },
    { "name": "chronic kidney disease" },
    { "name": "nephrotic syndrome" },
    { "name": "kidney stones" },
    { "name": "urinary tract infection" },
    { "name": "pyelonephritis" },
    { "name": "glomerulonephritis" },
    { "name": "hydronephrosis" },
    { "name": "polycystic kidney disease" },
    { "name": "renal artery stenosis" },
    { "name": "renal cell carcinoma" },
    { "name": "bladder infection" },
    { "name": "interstitial cystitis" },
    { "name": "prostatitis" },
    { "name": "benign prostatic hyperplasia" },
    { "name": "prostate cancer" },
    { "name": "testicular cancer" },
    { "name": "erectile dysfunction" },
    { "name": "male infertility" },
    { "name": "female infertility" },
    { "name": "ovarian cysts" },
    { "name": "endometriosis" },
    { "name": "uterine fibroids" },
    { "name": "polycystic ovary syndrome" },
    { "name": "menopause" },
    { "name": "pelvic inflammatory disease" },
    { "name": "cervical cancer" },
    { "name": "uterine cancer" },
    { "name": "ovarian cancer" },
    { "name": "breast cancer" },
    { "name": "vulvar cancer" },
    { "name": "vaginal cancer" },
    { "name": "human papillomavirus infection" },
    { "name": "genital herpes" },
    { "name": "trichomoniasis" },
    { "name": "bacterial vaginosis" },
    { "name": "yeast infection" },
    { "name": "pregnancy complications" },
    { "name": "preterm labor" },
    { "name": "pre-eclampsia" },
    { "name": "eclampsia" },
    { "name": "gestational diabetes" },
    { "name": "placenta previa" },
    { "name": "placental abruption" },
    { "name": "miscarriage" },
    { "name": "stillbirth" },
    { "name": "postpartum hemorrhage" },
    { "name": "postpartum depression" },
    { "name": "congenital heart disease" },
    { "name": "congenital hypothyroidism" },
    { "name": "congenital adrenal hyperplasia" },
    { "name": "cystic fibrosis" },
    { "name": "down syndrome" },
    { "name": "spina bifida" },
    { "name": "cleft lip and palate" },
    { "name": "muscular dystrophy" },
    { "name": "cerebral palsy" },
    { "name": "developmental delay" },
    { "name": "intellectual disability" },
    { "name": "autism spectrum disorder" },
    { "name": "attention deficit hyperactivity disorder" },
    { "name": "learning disabilities" },
    { "name": "speech and language disorders" },
    { "name": "hearing loss" },
    { "name": "vision impairment" },
    { "name": "childhood obesity" },
    { "name": "asthma" },
    { "name": "food allergies" },
    { "name": "eczema" },
    { "name": "gastroesophageal reflux disease" },
    { "name": "irritable bowel syndrome" },
    { "name": "crohn's disease" },
    { "name": "ulcerative colitis" },
    { "name": "celiac disease" },
    { "name": "lactose intolerance" },
    { "name": "peptic ulcer disease" },
    { "name": "gallstones" },
    { "name": "cholecystitis" },
    { "name": "pancreatitis" },
    { "name": "hepatitis" },
    { "name": "cirrhosis" },
    { "name": "liver cancer" },
    { "name": "fatty liver disease" },
    { "name": "alcoholic liver disease" },
    { "name": "wilson's disease" },
    { "name": "hemochromatosis" },
    { "name": "acute liver failure" },
    { "name": "chronic liver disease" },
    { "name": "liver transplant" },
    { "name": "hypertension" },
    { "name": "coronary artery disease" },
    { "name": "myocardial infarction" },
    { "name": "heart failure" },
    { "name": "arrhythmia" },
    { "name": "valvular heart disease" },
    { "name": "pericarditis" },
    { "name": "endocarditis" },
    { "name": "aortic aneurysm" },
    { "name": "deep vein thrombosis" },
    { "name": "pulmonary embolism" },
    { "name": "stroke" },
    { "name": "transient ischemic attack" },
    { "name": "peripheral artery disease" },
    { "name": "varicose veins" },
    { "name": "lymphedema" },
    { "name": "anemia" },
    { "name": "sickle cell disease" },
    { "name": "thalassemia" },
    { "name": "hemophilia" },
    { "name": "immune thrombocytopenic purpura" },
    { "name": "von willebrand disease" },
    { "name": "lymphoma" },
    { "name": "leukemia" },
    { "name": "multiple myeloma" },
    { "name": "bone marrow transplant" },
    { "name": "HIV/AIDS" },
    { "name": "tuberculosis" },
    { "name": "malaria" },
    { "name": "typhoid fever" },
    { "name": "cholera" },
    { "name": "dengue fever" },
    { "name": "yellow fever" },
    { "name": "ebola" },
    { "name": "lassa fever" },
    { "name": "zika virus" },
    { "name": "chikungunya" },
    { "name": "influenza" },
    { "name": "measles" },
    { "name": "mumps" },
    { "name": "rubella" },
    { "name": "whooping cough" },
    { "name": "hepatitis A" },
    { "name": "hepatitis B" },
    { "name": "hepatitis C" },
    { "name": "hepatitis D" },
    { "name": "hepatitis E" },
    { "name": "rabies" },
    { "name": "tetanus" },
    { "name": "polio" },
    { "name": "pneumonia" },
    { "name": "bronchitis" },
    { "name": "emphysema" },
    { "name": "chronic obstructive pulmonary disease" },
    { "name": "lung cancer" },
    { "name": "tuberculosis" },
    { "name": "pleural effusion" },
    { "name": "pulmonary hypertension" },
    { "name": "interstitial lung disease" },
    { "name": "asbestosis" },
    { "name": "silicosis" },
    { "name": "pulmonary fibrosis" },
    { "name": "sarcoidosis" },
    { "name": "pneumoconiosis" },
    { "name": "respiratory failure" },
    { "name": "sleep apnea" },
    { "name": "acute respiratory distress syndrome" },
    { "name": "chronic cough" },
    { "name": "asthma" },
    { "name": "allergic rhinitis" },
    { "name": "sinusitis" },
    { "name": "tonsillitis" },
    { "name": "pharyngitis" },
    { "name": "laryngitis" },
    { "name": "otitis media" },
    { "name": "otitis externa" },
    { "name": "hearing loss" },
    { "name": "meniere's disease" },
    { "name": "vestibular neuritis" },
    { "name": "labyrinthitis" },
    { "name": "tinnitus" },
    { "name": "vertigo" },
    { "name": "dizziness" },
    { "name": "balance disorder" },
    { "name": "nasal polyps" },
    { "name": "deviated septum" },
    { "name": "nosebleed" },
    { "name": "oral thrush" },
    { "name": "canker sores" },
    { "name": "oral cancer" },
    { "name": "tooth decay" },
    { "name": "gum disease" },
    { "name": "dental abscess" },
    { "name": "toothache" },
    { "name": "bad breath" },
    { "name": "dry mouth" },
    { "name": "oral herpes" },
    { "name": "burning mouth syndrome" },
    { "name": "temporomandibular joint disorder" },
    { "name": "bruxism" },
    { "name": "trigeminal neuralgia" },
    { "name": "bell's palsy" },
    { "name": "migraine" },
    { "name": "cluster headache" },
    { "name": "tension headache" },
    { "name": "sinus headache" },
    { "name": "rebound headache" },
    { "name": "cervicogenic headache" },
    { "name": "post-traumatic headache" },
    { "name": "chronic daily headache" },
    { "name": "primary stabbing headache" },
    { "name": "new daily persistent headache" },
    { "name": "idiopathic intracranial hypertension" },
    { "name": "temporal arteritis" },
    { "name": "intracranial hypotension" },
    { "name": "cranial neuralgia" },
    { "name": "facial pain" },
    { "name": "carpal tunnel syndrome" },
    { "name": "cubital tunnel syndrome" },
    { "name": "thoracic outlet syndrome" },
    { "name": "sciatica" },
    { "name": "lumbar radiculopathy" },
    { "name": "cervical radiculopathy" },
    { "name": "herniated disc" },
    { "name": "spinal stenosis" },
    { "name": "spondylolisthesis" },
    { "name": "ankylosing spondylitis" },
    { "name": "degenerative disc disease" },
    { "name": "facet joint syndrome" },
    { "name": "whiplash" },
    { "name": "chronic low back pain" },
    { "name": "chronic neck pain" },
    { "name": "chronic pain syndrome" },
    { "name": "fibromyalgia" },
    { "name": "myofascial pain syndrome" },
    { "name": "complex regional pain syndrome" },
    { "name": "phantom limb pain" },
    { "name": "diabetic neuropathy" },
    { "name": "peripheral neuropathy" },
    { "name": "autonomic neuropathy" },
    { "name": "trigeminal neuralgia" },
    { "name": "postherpetic neuralgia" },
    { "name": "thoracic outlet syndrome" },
    { "name": "piriformis syndrome" },
    { "name": "tarsal tunnel syndrome" },
    { "name": "restless legs syndrome" },
    { "name": "charcot-marie-tooth disease" },
    { "name": "muscular dystrophy" },
    { "name": "myasthenia gravis" },
    { "name": "amyotrophic lateral sclerosis" },
    { "name": "multiple sclerosis" },
    { "name": "parkinson's disease" },
    { "name": "huntington's disease" },
    { "name": "essential tremor" },
    { "name": "dystonia" },
    { "name": "cerebral palsy" },
    { "name": "spinal muscular atrophy" },
    { "name": "hereditary spastic paraplegia" },
    { "name": "stroke" },
    { "name": "transient ischemic attack" },
    { "name": "brain aneurysm" },
    { "name": "arteriovenous malformation" },
    { "name": "subarachnoid hemorrhage" },
    { "name": "intracerebral hemorrhage" },
    { "name": "subdural hematoma" },
    { "name": "epidural hematoma" },
    { "name": "concussion" },
    { "name": "traumatic brain injury" },
    { "name": "encephalitis" },
    { "name": "meningitis" },
    { "name": "brain abscess" },
    { "name": "hydrocephalus" },
    { "name": "normal pressure hydrocephalus" },
    { "name": "idiopathic intracranial hypertension" },
    { "name": "chiari malformation" },
    { "name": "spina bifida" },
    { "name": "cerebral edema" },
    { "name": "seizure disorder" },
    { "name": "epilepsy" },
    { "name": "febrile seizure" },
    { "name": "status epilepticus" },
    { "name": "absence seizure" },
    { "name": "tonic-clonic seizure" },
    { "name": "myoclonic seizure" },
    { "name": "atonic seizure" },
    { "name": "focal seizure" },
    { "name": "temporal lobe epilepsy" },
    { "name": "frontal lobe epilepsy" },
    { "name": "parietal lobe epilepsy" },
    { "name": "occipital lobe epilepsy" },
    { "name": "benign rolandic epilepsy" },
    { "name": "juvenile myoclonic epilepsy" },
    { "name": "lennox-gastaut syndrome" },
    { "name": "dravet syndrome" },
    { "name": "tuberous sclerosis" },
    { "name": "sturge-weber syndrome" },
    { "name": "nervous system tumor" },
    { "name": "brain tumor" },
    { "name": "meningioma" },
    { "name": "glioblastoma" },
    { "name": "astrocytoma" },
    { "name": "oligodendroglioma" },
    { "name": "ependymoma" },
    { "name": "medulloblastoma" },
    { "name": "pituitary tumor" },
    { "name": "schwannoma" },
    { "name": "neurofibroma" },
    { "name": "metastatic brain tumor" },
    { "name": "spinal cord tumor" },
    { "name": "spinal meningioma" },
    { "name": "spinal schwannoma" },
    { "name": "spinal ependymoma" },
    { "name": "spinal astrocytoma" },
    { "name": "primary bone cancer" },
    { "name": "osteosarcoma" },
    { "name": "ewing's sarcoma" },
    { "name": "chondrosarcoma" },
    { "name": "fibrosarcoma" },
    { "name": "chordoma" },
    { "name": "giant cell tumor of bone" },
    { "name": "multiple myeloma" },
    { "name": "bone metastasis" },
    { "name": "primary liver cancer" },
    { "name": "hepatocellular carcinoma" },
    { "name": "cholangiocarcinoma" },
    { "name": "liver metastasis" },
    { "name": "primary lung cancer" },
    { "name": "non-small cell lung cancer" },
    { "name": "small cell lung cancer" },
    { "name": "lung metastasis" },
    { "name": "primary breast cancer" },
    { "name": "ductal carcinoma in situ" },
    { "name": "invasive ductal carcinoma" },
    { "name": "invasive lobular carcinoma" },
    { "name": "inflammatory breast cancer" },
    { "name": "breast metastasis" },
    { "name": "primary prostate cancer" },
    { "name": "prostate metastasis" },
    { "name": "primary colorectal cancer" },
    { "name": "colorectal metastasis" },
    { "name": "primary pancreatic cancer" },
    { "name": "pancreatic metastasis" },
    { "name": "primary esophageal cancer" },
    { "name": "esophageal metastasis" },
    { "name": "primary stomach cancer" },
    { "name": "stomach metastasis" },
    { "name": "primary ovarian cancer" },
    { "name": "ovarian metastasis" },
    { "name": "primary uterine cancer" },
    { "name": "uterine metastasis" },
    { "name": "primary cervical cancer" },
    { "name": "cervical metastasis" },
    { "name": "primary bladder cancer" },
    { "name": "bladder metastasis" },
    { "name": "primary kidney cancer" },
    { "name": "renal cell carcinoma" },
    { "name": "kidney metastasis" },
    { "name": "primary thyroid cancer" },
    { "name": "papillary thyroid cancer" },
    { "name": "follicular thyroid cancer" },
    { "name": "medullary thyroid cancer" },
    { "name": "anaplastic thyroid cancer" },
    { "name": "thyroid metastasis" },
    { "name": "primary skin cancer" },
    { "name": "basal cell carcinoma" },
    { "name": "squamous cell carcinoma" },
    { "name": "melanoma" },
    { "name": "skin metastasis" },
    { "name": "primary head and neck cancer" },
    { "name": "oral cancer" },
    { "name": "laryngeal cancer" },
    { "name": "nasopharyngeal cancer" },
    { "name": "oropharyngeal cancer" },
    { "name": "hypopharyngeal cancer" },
    { "name": "head and neck metastasis" },
    { "name": "primary brain cancer" },
    { "name": "glioma" },
    { "name": "meningioma" },
    { "name": "pituitary adenoma" },
    { "name": "acoustic neuroma" },
    { "name": "brain metastasis" },
    { "name": "primary spinal cord cancer" },
    { "name": "spinal cord metastasis" },
    { "name": "primary bone marrow cancer" },
    { "name": "leukemia" },
    { "name": "multiple myeloma" },
    { "name": "bone marrow metastasis" },
    { "name": "primary lymphoma" },
    { "name": "hodgkin lymphoma" },
    { "name": "non-hodgkin lymphoma" },
    { "name": "lymphoma metastasis" },
    { "name": "primary blood cancer" },
    { "name": "acute lymphoblastic leukemia" },
    { "name": "acute myeloid leukemia" },
    { "name": "chronic lymphocytic leukemia" },
    { "name": "chronic myeloid leukemia" },
    { "name": "myelodysplastic syndromes" },
    { "name": "myeloproliferative disorders" },
    { "name": "aplastic anemia" },
    { "name": "hemolytic anemia" },
    { "name": "iron-deficiency anemia" },
    { "name": "vitamin B12 deficiency anemia" },
    { "name": "folate deficiency anemia" },
    { "name": "thalassemia" },
    { "name": "sickle cell disease" },
    { "name": "hereditary spherocytosis" },
    { "name": "hereditary elliptocytosis" },
    { "name": "g6pd deficiency" },
    { "name": "pyruvate kinase deficiency" },
    { "name": "congenital dyserythropoietic anemia" },
    { "name": "diamond-blackfan anemia" },
    { "name": "fanconi anemia" },
    { "name": "transfusion-related complications" },
    { "name": "hemophilia A" },
    { "name": "hemophilia B" },
    { "name": "von willebrand disease" },
    { "name": "immune thrombocytopenic purpura" },
    { "name": "thrombotic thrombocytopenic purpura" },
    { "name": "heparin-induced thrombocytopenia" },
    { "name": "disseminated intravascular coagulation" },
    { "name": "hemophagocytic lymphohistiocytosis" },
    { "name": "hypercoagulable state" },
    { "name": "deep vein thrombosis" },
    { "name": "pulmonary embolism" },
    { "name": "arterial thrombosis" },
    { "name": "antiphospholipid syndrome" },
    { "name": "factor V Leiden mutation" },
    { "name": "prothrombin gene mutation" },
    { "name": "protein C deficiency" },
    { "name": "protein S deficiency" },
    { "name": "antithrombin deficiency" },
    { "name": "hyperhomocysteinemia" },
    { "name": "paroxysmal nocturnal hemoglobinuria" },
    { "name": "myelodysplastic syndrome" },
    { "name": "polycythemia vera" },
    { "name": "essential thrombocythemia" },
    { "name": "primary myelofibrosis" },
    { "name": "mastocytosis" },
    { "name": "systemic mastocytosis" },
    { "name": "cutaneous mastocytosis" },
    { "name": "monoclonal gammopathy of undetermined significance" },
    { "name": "waldenstrom macroglobulinemia" },
    { "name": "amyloidosis" },
    { "name": "light chain deposition disease" },
    { "name": "plasma cell leukemia" },
    { "name": "cryoglobulinemia" },
    { "name": "hyperviscosity syndrome" },
    { "name": "post-transplant lymphoproliferative disorder" },
    { "name": "graft versus host disease" },
    { "name": "bone marrow transplant complications" },
    { "name": "splenomegaly" },
    { "name": "hypersplenism" },
    { "name": "asplenia" },
    { "name": "functional asplenia" },
    { "name": "anaphylaxis" },
    { "name": "angioedema" },
    { "name": "urticaria" },
    { "name": "allergic rhinitis" },
    { "name": "allergic conjunctivitis" },
    { "name": "food allergy" },
    { "name": "drug allergy" },
    { "name": "latex allergy" },
    { "name": "insect sting allergy" },
    { "name": "allergic asthma" },
    { "name": "atopic dermatitis" },
    { "name": "contact dermatitis" },
    { "name": "eosinophilic esophagitis" },
    { "name": "eosinophilic gastroenteritis" },
    { "name": "eosinophilic colitis" },
    { "name": "eosinophilic pneumonia" },
    { "name": "hypereosinophilic syndrome" },
    { "name": "mast cell activation syndrome" },
    { "name": "autoimmune hemolytic anemia" },
    { "name": "cold agglutinin disease" },
    { "name": "paroxysmal cold hemoglobinuria" },
    { "name": "warm autoimmune hemolytic anemia" },
    { "name": "autoimmune neutropenia" },
    { "name": "autoimmune thrombocytopenia" },
    { "name": "evans syndrome" },
    { "name": "antibody deficiency syndromes" },
    { "name": "common variable immunodeficiency" },
    { "name": "selective IgA deficiency" },
    { "name": "x-linked agammaglobulinemia" },
    { "name": "hyper IgM syndrome" },
    { "name": "IgG subclass deficiency" },
    { "name": "specific antibody deficiency" },
    { "name": "complement deficiency" },
    { "name": "chronic granulomatous disease" },
    { "name": "leukocyte adhesion deficiency" },
    { "name": "chediak-higashi syndrome" },
    { "name": "griscelli syndrome" },
    { "name": "hereditary angioedema" },
    { "name": "hereditary spherocytosis" },
    { "name": "hereditary elliptocytosis" },
    { "name": "g6pd deficiency" },
    { "name": "pyruvate kinase deficiency" },
    { "name": "congenital dyserythropoietic anemia" },
    { "name": "diamond-blackfan anemia" },
    { "name": "fanconi anemia" },
    { "name": "shwachman-diamond syndrome" },
    { "name": "dyskeratosis congenita" },
    { "name": "congenital neutropenia" },
    { "name": "cyclic neutropenia" },
    {"name":"Road accident"}
    ]

    export default disorders